[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''elseif specific_vars and (card_type == 'Default' or card_type == 'Enhanced') then'''
position = 'before'
payload = '''elseif specific_vars and type(specific_vars.collect) == "table" then
    full_UI_table.name = {}
    localize{type = 'other', key = specific_vars.collect.key, set = 'Other', nodes = full_UI_table.name, vars = {}}
    full_UI_table.name = full_UI_table.name[1]'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''localize{type = 'other', key = _c.key, nodes = desc_nodes, vars = specific_vars or _c.vars}'''
position = 'after'
payload = '''elseif specific_vars and type(specific_vars.collect) == "table" then
    local config_thing = specific_vars.collect.config
    if specific_vars.collect.name == "Flint Card" then
        loc_vars = {localize("Hearts", 'suits_plural'), localize("Diamonds", 'suits_plural'), config_thing.mult}
    elseif specific_vars.collect.name == "Eye Card" then
        loc_vars = {localize("Spades", 'suits_plural'), localize("Clubs", 'suits_plural'), config_thing.chips}
    elseif specific_vars.collect.name == "Scholar's Mate" then
        loc_vars = {localize("Queen", 'ranks'), config_thing.chips, config_thing.mult}
    elseif specific_vars.collect.name == "Scandinavian Defense" then
        loc_vars = {localize("Queen", 'ranks'), config_thing.chips, config_thing.mult, localize("Spades", 'suits_plural'), localize("Clubs", 'suits_plural')}
    elseif specific_vars.collect.name == "Double Up" then
        loc_vars = {config_thing.retriggers}
    elseif specific_vars.collect.name == "Playable Joker" then
        loc_vars = {G.GAME.probabilities.normal, config_thing.odds}
        info_queue[#info_queue + 1] = G.P_CENTERS['e_foil']
        info_queue[#info_queue + 1] = G.P_CENTERS['e_holo']
        info_queue[#info_queue + 1] = G.P_CENTERS['e_polychrome']
    elseif specific_vars.collect.name == "Sunflower" then
        loc_vars = {config_thing.chips, config_thing.gain}
    elseif specific_vars.collect.name == "Rules Card" then
        loc_vars = {config_thing.discards}
    elseif specific_vars.collect.name == "Wild Draw 4" then
        loc_vars = {config_thing.chips, config_thing.cards}
    elseif specific_vars.collect.name == "Jack in a Box" then
        loc_vars = {config_thing.chips, config_thing.scores, config_thing.scored}
    elseif specific_vars.collect.name == "2mbstone" then
        loc_vars = {config_thing.chips, G.GAME.probabilities.normal, config_thing.odds}
        info_queue[#info_queue + 1] = G.P_CENTERS['c_death']
    end
    localize{type = 'descriptions', key = specific_vars.collect.key, set = "CustomCard", nodes = desc_nodes, vars = loc_vars}
    if specific_vars.bonus_chips then
        localize{type = 'other', key = 'card_extra_chips', nodes = desc_nodes, vars = {specific_vars.bonus_chips}}
    end
    if specific_vars and specific_vars.bonus_mult then
        localize{type = 'other', key = 'card_extra_mult', nodes = desc_nodes, vars = {specific_vars.bonus_mult}}
    end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''bonus_chips = (self.ability.bonus + (self.ability.perma_bonus or 0)) > 0 and (self.ability.bonus + (self.ability.perma_bonus or 0)) or nil,'''
position = 'after'
payload = '''collect = (self.ability.trading or nil),'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''scoring_hand[i].lucky_trigger = nil'''
position = 'before'
payload = '''for k=1, #scoring_hand do
    local eval = scoring_hand[k]:calculate_exotic({cardarea = G.play, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, other_card = scoring_hand[i], individual = true})
    if eval then 
        for l = 1, #eval do
            table.insert(effects, eval[l])
        end
    end
end
for k=1, #G.hand.cards do
    local eval = G.hand.cards[k]:calculate_exotic({cardarea = G.play, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, other_card = scoring_hand[i], individual = true})
    if eval then 
        for l = 1, #eval do
            table.insert(effects, eval[l])
        end
    end
end
local exotic_eval = scoring_hand[i]:calculate_exotic({cardarea = G.play, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, playing_card_main = true})
if exotic_eval then
    for l = 1, #exotic_eval do
        table.insert(effects, exotic_eval[l])
    end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''self.P_LOCKED = {}'''
position = 'after'
payload = '''self.P_TRADING = {
    flint_card = {order = 1, key = 'flint_card', unlocked = true, discovered = true, atlas = 'pc_trading', cost = 1, name = "Flint Card", pos = {x=1,y=0}, set = "CustomCard", config = {mult = 5}, base = "H_A"},
    scholar_mate = {order = 2, key = 'scholar_mate', unlocked = true, discovered = true, atlas = 'pc_trading', cost = 1, name = "Scholar's Mate", pos = {x=3,y=0}, set = "CustomCard", config = {chips = 10, mult = 7}, base = "S_Q"},
    scandinavian_defense = {order = 3, key = 'scandinavian_defense', unlocked = true, discovered = true, atlas = 'pc_trading', cost = 1, name = "Scandinavian Defense", pos = {x=2,y=0}, set = "CustomCard", config = {chips = 10, mult = 7}, base = "S_Q"},
    double_up = {order = 4, key = 'double_up', unlocked = true, discovered = true, atlas = 'pc_trading', cost = 1, name = "Double Up", pos = {x=3,y=1}, set = "CustomCard", config = {retriggers = 1}, base = "S_Q"},
    eye_card = {order = 5, key = 'eye_card', unlocked = true, discovered = true, atlas = 'pc_trading', cost = 1, name = "Eye Card", pos = {x=4,y=1}, set = "CustomCard", config = {chips = 40}, base = "C_A"},
    playable_joker = {order = 6, key = 'playable_joker', unlocked = true, discovered = true, atlas = 'pc_trading', cost = 1, name = "Playable Joker", pos = {x=0,y=0}, set = "CustomCard", config = {odds = 4}, base = "S_2"},
    sunflower = {order = 7, key = 'sunflower', unlocked = true, discovered = true, atlas = 'pc_trading', cost = 1, name = "Sunflower", pos = {x=0,y=2}, set = "CustomCard", config = {chips = 8, gain = 2}, base = "D_8"},
    rules_card = {order = 8, key = 'rules_card', unlocked = true, discovered = true, atlas = 'pc_trading', cost = 1, name = "Rules Card", pos = {x=1,y=2}, set = "CustomCard", config = {discards = 1}, base = "S_A"},
    wild_draw_4 = {order = 9, key = 'wild_draw_4', unlocked = true, discovered = true, atlas = 'pc_trading', cost = 1, name = "Wild Draw 4", pos = {x=2,y=2}, set = "CustomCard", config = {chips = 4, cards = 4}, base = "C_4"},
    jack_in_a_box = {order = 10, key = 'jack_in_a_box', unlocked = true, discovered = true, atlas = 'pc_trading', cost = 1, name = "Jack in a Box", pos = {x=3,y=2}, set = "CustomCard", config = {chips = 10, scores = 5, scored = 0}, base = "C_J"},
    tombstone = {order = 11, key = 'tombstone', unlocked = true, discovered = true, atlas = 'pc_trading', cost = 1, name = "2mbstone", pos = {x=4,y=2}, set = "CustomCard", config = {chips = 2, odds = 3}, base = "S_2"},
 }'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''self.children.center:set_sprite_pos(_center.pos)'''
position = 'after'
payload = '''if self.ability and self.ability.trading and self.ability.trading.atlas then
    self.children.center.atlas = G.ASSET_ATLAS[self.ability.trading.atlas]
    self.children.center:set_sprite_pos(self.ability.trading.pos)
end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''elseif self.config.center.consumeable and self.config.center.demo then'''
position = 'before'
payload = '''elseif self.ability and self.ability.trading and self.ability.trading.atlas then
    self.children.center = Sprite(self.T.x, self.T.y, self.T.w, self.T.h, G.ASSET_ATLAS[self.ability.trading.atlas], self.ability.trading.pos)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''if not strip_edition then'''
position = 'before'
payload = '''new_card:set_sprites(new_card.config.center)'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''for i=1, #pures do'''
position = 'before'
payload = '''for k=1, #G.play.cards do
    local eval = G.play.cards[k]:calculate_exotic({cardarea = G.play, full_hand = G.play.cards, scoring_name = text, poker_hands = poker_hands, does_score = true})
    if eval then
        local inside = false
        for j=1, #scoring_hand do
            if scoring_hand[j] == G.play.cards[k] then
                inside = true
            end
        end
        if not inside then
            table.insert(scoring_hand, G.play.cards[k])
        end
    end
end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''function Card:is_suit(suit, bypass_debuff, flush_calc)'''
position = 'after'
payload = '''   if self.ability and self.ability.trading then
        local eval = self:calculate_exotic({bypass_debuff = bypass_debuff, flush_calc = flush_calc, is_suit = suit})
        if eval then
            return eval
        end
    end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''function Card:get_id()'''
position = 'after'
payload = '''   if self.ability and self.ability.trading then
        local eval = self:calculate_exotic({get_id = true})
        if eval then
            return eval
        end
    end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''function Card:can_use_consumeable(any_state, skip_check)'''
position = 'after'
payload = '''   if (self.ability.name == 'Strength') or self.ability.consumeable.suit_conv then 
        for i = 1, #G.hand.highlighted do
            if G.hand.highlighted[i].ability and G.hand.highlighted[i].ability.trading then return false end
        end
    end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''local eval = eval_card(scoring_hand[i], {repetition_only = true,cardarea = G.play, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, repetition = true})'''
position = 'after'
payload = '''for l=1, #scoring_hand do
    local eval = scoring_hand[l]:calculate_exotic({cardarea = G.play, other_card = scoring_hand[i], repetition = true, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands}, {})
    if next(eval) then
        for _, minieval in ipairs(eval) do
            if minieval.repetitions then
                for h = 1, minieval.repetitions do
                    reps[#reps+1] = {jokers = {
                        message = minieval.message,
                        card = minieval.cards[#minieval.cards],
                        repetitions = minieval.repetitions,
                        cards = minieval.cards,
                    }}
                end
            end
        end
    end
end
for l=1, #G.hand.cards do
    local eval = G.hand.cards[l]:calculate_exotic({cardarea = G.play, other_card = scoring_hand[i], repetition = true, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands}, {})
    if next(eval) then
        for _, minieval in ipairs(eval) do
            if minieval.repetitions then
                for h = 1, minieval.repetitions do
                    reps[#reps+1] = {jokers = {
                        message = minieval.message,
                        card = minieval.cards[#minieval.cards],
                        repetitions = minieval.repetitions,
                        cards = minieval.cards,
                    }}
                end
            end
        end
    end
end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''card_eval_status_text((reps[j].jokers or reps[j].seals).card, 'jokers', nil, nil, nil, (reps[j].jokers or reps[j].seals))'''
position = 'after'
payload = '''if (reps[j].jokers or reps[j].seals).cards then
    for k = #(reps[j].jokers or reps[j].seals).cards - 1, 1, -1 do
        card_eval_status_text((reps[j].jokers or reps[j].seals).cards[k], 'jokers', nil, nil, nil, (reps[j].jokers or reps[j].seals))
    end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''table.sort(self.P_CENTER_POOLS["Seal"], function (a, b) return a.order < b.order end)'''
position = 'after'
payload = '''table.sort(self.P_CENTER_POOLS["Exotic"], function (a, b) return a.order < b.order end)'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''for k, v in pairs(self.P_STAKES) do'''
position = 'before'
payload = '''for k, v in pairs(self.P_TRADING) do
    v.key = k
    if not v.wip and not v.demo then 
        table.insert(self.P_CENTER_POOLS["Exotic"], v)
    end
end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''Stake = {},'''
position = 'after'
payload = '''Exotic = {},'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''function Card:set_ability(center, initial, delay_sprites)'''
position = 'after'
payload = '''   if self.ability and self.ability.trading and (center ~= G.P_CENTERS["m_pc_trading"]) then
        self.ability.trading = nil
    end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''eval = eval_card(G.hand.highlighted[i], {discard = true, full_hand = G.hand.highlighted})'''
position = 'after'
payload = '''local special_eval = G.hand.highlighted[i]:calculate_exotic({discard = true, full_hand = G.hand.highlighted}, {})
if special_eval.remove then
    eval.remove = true
end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''local hand_text_set = false'''
position = 'before'
payload = '''for k=1, #G.play.cards do
    G.play.cards[k]:calculate_exotic({cardarea = G.play, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, before = true})
end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''function Card:is_face(from_boss)'''
position = 'after'
payload = '''if self.ability and self.ability.trading then
        local eval = self:calculate_exotic({from_boss = from_boss, is_face = true})
        if eval then
            return eval
        end
    end'''
match_indent = true