[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''elseif specific_vars and (card_type == 'Default' or card_type == 'Enhanced') then'''
position = 'before'
payload = '''elseif specific_vars and type(specific_vars.collect) == "table" then
    full_UI_table.name = {}
    localize{type = 'other', key = specific_vars.collect.key, set = 'Other', nodes = full_UI_table.name, vars = {localize(specific_vars.value, 'ranks'), localize(specific_vars.suit, 'suits_plural'), colours = {specific_vars.colour}}}
    full_UI_table.name = full_UI_table.name[1]'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''localize{type = 'other', key = _c.key, nodes = desc_nodes, vars = specific_vars or _c.vars}'''
position = 'after'
payload = '''elseif specific_vars and type(specific_vars.collect) == "table" then
    local config_thing = specific_vars.collect.config
    if specific_vars.collect.name == "Flint Card" then
        loc_vars = {localize("Hearts", 'suits_plural'), localize("Diamonds", 'suits_plural'), config_thing.mult}
    elseif specific_vars.collect.name == "Scholar's Mate" then
        loc_vars = {localize("Queen", 'ranks'), config_thing.chips, config_thing.mult}
    elseif specific_vars.collect.name == "Scandinavian Defense" then
        loc_vars = {localize("Queen", 'ranks'), config_thing.chips, config_thing.mult, localize("Spades", 'suits_plural'), localize("Clubs", 'suits_plural')}
    end
    localize{type = 'descriptions', key = specific_vars.collect.key, set = "CustomCard", nodes = desc_nodes, vars = loc_vars}'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''bonus_chips = (self.ability.bonus + (self.ability.perma_bonus or 0)) > 0 and (self.ability.bonus + (self.ability.perma_bonus or 0)) or nil,'''
position = 'after'
payload = '''collect = (self.ability.trading or nil),'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''scoring_hand[i].lucky_trigger = nil'''
position = 'before'
payload = '''for k=1, #scoring_hand do
    local reps0 = scoring_hand[k]:calculate_exotic({get_self_retriggers = true, cardarea = G.play, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands})
    for q=1, #reps0 do
        if reps0[q] ~= 1 then
            card_eval_status_text((reps0[q].jokers or reps0[q].seals).card, 'jokers', nil, nil, nil, (reps0[q].jokers or reps0[q].seals))
            if reps0[q].from_retrigger then
                card_eval_status_text(reps0[q].from_retrigger.card, 'jokers', nil, nil, nil, reps0[q].from_retrigger)
            end
        end
        local eval = scoring_hand[k]:calculate_exotic({cardarea = G.play, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, other_card = scoring_hand[i], individual = true})
        if eval then 
            table.insert(effects, eval)
        elseif not eval and (reps0[q] == 1) then
            break
        end
    end
end
for k=1, #G.hand.cards do
    local reps0 = G.hand.cards[k]:calculate_exotic({get_self_retriggers = true, cardarea = G.play, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands})
    for q=1, #reps0 do
        if reps0[q] ~= 1 then
            card_eval_status_text((reps0[q].jokers or reps0[q].seals).card, 'jokers', nil, nil, nil, (reps0[q].jokers or reps0[q].seals))
            if reps0[q].from_retrigger then
                card_eval_status_text(reps0[q].from_retrigger.card, 'jokers', nil, nil, nil, reps0[q].from_retrigger)
            end
        end
        local eval = G.hand.cards[k]:calculate_exotic({cardarea = G.play, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, other_card = scoring_hand[i], individual = true})
        if eval then 
            table.insert(effects, eval)
        elseif not eval and (reps0[q] == 1) then
            break
        end
    end
end
local exotic_eval = scoring_hand[i]:calculate_exotic({cardarea = G.play, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, playing_card_main = true})
if exotic_eval then 
    table.insert(effects, exotic_eval)
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''self.P_LOCKED = {}'''
position = 'after'
payload = '''self.P_TRADING = {
    flint_card = {order = 1, key = 'flint_card', unlocked = true, discovered = true, atlas = 'pc_trading', cost = 1, name = "Flint Card", pos = {x=1,y=0}, set = "CustomCard", config = {mult = 4}, base = "H_A"},
    scholar_mate = {order = 2, key = 'scholar_mate', unlocked = true, discovered = true, atlas = 'pc_trading', cost = 1, name = "Scholar's Mate", pos = {x=3,y=0}, set = "CustomCard", config = {chips = 10, mult = 7}, base = "S_Q"},
    scandinavian_defense = {order = 3, key = 'scandinavian_defense', unlocked = true, discovered = true, atlas = 'pc_trading', cost = 1, name = "Scandinavian Defense", pos = {x=2,y=0}, set = "CustomCard", config = {chips = 10, mult = 7}, base = "S_Q"},
 }'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''self.children.center:set_sprite_pos(_center.pos)'''
position = 'after'
payload = '''if self.ability and self.ability.trading and self.ability.trading.atlas then
    self.children.center.atlas = G.ASSET_ATLAS[self.ability.trading.atlas]
    self.children.center:set_sprite_pos(self.ability.trading.pos)
end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''elseif self.config.center.consumeable and self.config.center.demo then'''
position = 'before'
payload = '''elseif self.ability and self.ability.trading and self.ability.trading.atlas then
    self.children.center = Sprite(self.T.x, self.T.y, self.T.w, self.T.h, G.ASSET_ATLAS[self.ability.trading.atlas], self.ability.trading.pos)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''if not strip_edition then'''
position = 'before'
payload = '''new_card:set_sprites(new_card.config.center)'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''for i=1, #pures do'''
position = 'before'
payload = '''for k=1, #G.play.cards do
    local eval = G.play.cards[k]:calculate_exotic({cardarea = G.play, full_hand = G.play.cards, scoring_name = text, poker_hands = poker_hands, does_score = true})
    if eval then
        local inside = false
        for j=1, #scoring_hand do
            if scoring_hand[j] == G.play.cards[k] then
                inside = true
            end
        end
        if not inside then
            table.insert(scoring_hand, G.play.cards[k])
        end
    end
end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''function Card:is_suit(suit, bypass_debuff, flush_calc)'''
position = 'after'
payload = '''   if self.ability and self.ability.trading then
        local eval = self:calculate_exotic({bypass_debuff = bypass_debuff, flush_calc = flush_calc, is_suit = suit})
        if eval then
            return eval
        end
    end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''function Card:get_id()'''
position = 'after'
payload = '''   if self.ability and self.ability.trading then
        local eval = self:calculate_exotic({get_id = true})
        if eval then
            return eval
        end
    end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''function Card:can_use_consumeable(any_state, skip_check)'''
position = 'after'
payload = '''   if (self.ability.name == 'Strength') or self.ability.consumeable.suit_conv or self.ability.consumeable.mod_conv then 
        for i = 1, #G.hand.highlighted do
            if G.hand.highlighted[i].ability and G.hand.highlighted[i].ability.trading then return false end
        end
    end'''
match_indent = true